version: '1'
services:
  database:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "53306:3306"
volumes:
  database-data: